Check if zstd submodule is cloned
Because now without submodule, the not clear error message is showed:

```
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/Users/xxx/zstd-rs/target/debug/build/zstd-sys-49975c690f361f7a/out/libzstd.a" with args "ar" did not execute successfully (status code exit code: 1).
```